spring:
  profiles: cc-master
  datasource:
    url: jdbc:mysql://passport-mysql-master:3306/skyid?useUnicode=true&amp;characterEncoding=utf-8
    username: skyid
    password: skyid@)!$
    driver-class-name: com.mysql.jdbc.Driver